"use client";

import { ArrowLeft, Check, Printer, Save, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import "../commerce-pages.css";

type QuoteItem={name:string;quantity:number;price:number};type QuoteDraft={source?:string;branch?:string;items?:QuoteItem[];services?:QuoteItem[];subtotal?:number;discount?:number;shippingFee?:number;total?:number};
const money=(n:number)=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP",maximumFractionDigits:0}).format(n||0);

export default function QuotePage(){
  const [draft,setDraft]=useState<QuoteDraft>({items:[]});const [customer,setCustomer]=useState({name:"",email:"",phone:""});const [status,setStatus]=useState("");const [reference,setReference]=useState("TS-Q-PENDING");
  useEffect(()=>{const timer=window.setTimeout(()=>{try{setDraft(JSON.parse(localStorage.getItem("pclogic-quote-draft")??"{}") as QuoteDraft);}catch{}const digits=new Uint32Array(1);crypto.getRandomValues(digits);setReference(`TS-Q-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${String(1000+digits[0]%9000)}`);void fetch("/api/customer/auth",{cache:"no-store"}).then((r)=>r.json()).then((b:{customer?:{name:string;email:string;phone:string}})=>{if(b.customer)setCustomer(b.customer);});},0);return()=>window.clearTimeout(timer);},[]);
  const items=[...(draft.items??[]),...(draft.services??[]).map((item)=>({...item,quantity:item.quantity??1}))];const subtotal=Number(draft.subtotal??items.reduce((sum,item)=>sum+item.price*item.quantity,0));const total=Number(draft.total??subtotal-Number(draft.discount??0)+Number(draft.shippingFee??0));
  async function save(){const response=await fetch("/api/customer/portal",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"quote",title:`Quotation ${reference}`,payload:{...draft,customer,reference,validUntil:new Date(Date.now()+7*86400000).toISOString()}})});const body=await response.json() as {error?:string;reference?:string};setStatus(response.ok?`Saved to your account as ${body.reference}.`:body.error??"Sign in to save this quotation.");}
  return <main className="commerce-page"><header className="commerce-page-header"><Link href="/" className="brand"><span>TECH <span>SYSTEMS</span></span></Link><nav><Link href="/shop"><ArrowLeft/>Back to store</Link><Link href="/account">My account</Link></nav></header><section className="quote-shell"><article className="quote-sheet"><header className="quote-head"><div><div className="brand"><span>TECH <span>SYSTEMS</span></span></div><p>COMPUTERS · SECURITY · NETWORKS</p></div><aside><span>Demo quotation</span><strong>{reference}</strong><small>Valid for 7 days · subject to demo stock</small></aside></header><section className="quote-customer"><label>Prepared for<input value={customer.name} onChange={(e)=>setCustomer({...customer,name:e.target.value})} placeholder="Customer name"/></label><label>Email<input value={customer.email} onChange={(e)=>setCustomer({...customer,email:e.target.value})} placeholder="Email address"/></label><label>Mobile<input value={customer.phone} onChange={(e)=>setCustomer({...customer,phone:e.target.value})} placeholder="Mobile number"/></label></section><table className="quote-lines"><thead><tr><th>Description</th><th>Qty</th><th>Unit price</th><th>Line total</th></tr></thead><tbody>{items.map((item,index)=><tr key={`${item.name}-${index}`}><td>{item.name}</td><td>{item.quantity}</td><td>{money(item.price)}</td><td>{money(item.price*item.quantity)}</td></tr>)}{!items.length&&<tr><td colSpan={4}>No quotation items were found. Return to the shop or builder and choose “Quote.”</td></tr>}</tbody></table><div className="quote-totals"><div><span>Products</span><b>{money(subtotal)}</b></div>{Number(draft.discount)>0&&<div><span>Promotion</span><b>−{money(Number(draft.discount))}</b></div>}{Number(draft.shippingFee)>0&&<div><span>Delivery estimate</span><b>{money(Number(draft.shippingFee))}</b></div>}<div className="total"><span>Quoted total</span><b>{money(total)}</b></div></div><div className="quote-notes"><ShieldCheck/> This is a demonstration quotation only. It does not reserve stock, process payment, create a tax invoice, or guarantee a final selling price. Demo staff confirms exact availability, assembly lead time, warranty terms, and final charges.</div>{status&&<p className="account-message"><Check/> {status}</p>}</article><div className="quote-actions"><Link href="/shop"><ArrowLeft/>Edit order</Link><button onClick={()=>window.print()}><Printer/>Print / save PDF</button><button className="primary" onClick={save}><Save/>Save to account</button></div></section></main>;
}
