"use client";

import { ArrowLeft, Boxes, Check, Eye, EyeOff, FileText, Heart, LogOut, Package, Plus, RefreshCw, RotateCcw, Settings, ShieldCheck, ShoppingBag, UserRound, Wrench } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import "../commerce-pages.css";

type Row=Record<string,string|number|null>;type Customer={id:string;email:string;name:string;phone:string;addresses:string[]};type Portal={customer:Customer;orders:Row[];items:Row[];records:Row[]};type Tab="overview"|"orders"|"builds"|"wishlist"|"returns"|"profile";
const money=(n:number)=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP",maximumFractionDigits:0}).format(n||0);const date=(v:unknown)=>v?new Intl.DateTimeFormat("en-PH",{dateStyle:"medium",timeStyle:"short"}).format(new Date(String(v).replace(" ","T")+"Z")):"—";const parse=(v:unknown)=>{try{return JSON.parse(String(v??"{}")) as Record<string,unknown>;}catch{return {};}};

export default function AccountPage(){
  const [auth,setAuth]=useState<"checking"|"signed-out"|"signed-in">("checking");const [mode,setMode]=useState<"login"|"register">("login");const [showPassword,setShowPassword]=useState(false);const [form,setForm]=useState({name:"",email:"",phone:"",password:""});const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [portal,setPortal]=useState<Portal|null>(null);const [tab,setTab]=useState<Tab>("overview");const [returnForm,setReturnForm]=useState({orderNumber:"",productName:"",reason:"",evidence:""});const [profile,setProfile]=useState({name:"",phone:"",addresses:""});
  const load=useCallback(async()=>{const response=await fetch("/api/customer/portal",{cache:"no-store"});if(response.status===401){setAuth("signed-out");setPortal(null);return;}const body=await response.json() as Portal&{error?:string};if(response.ok){setPortal(body);setAuth("signed-in");setProfile({name:body.customer.name,phone:body.customer.phone,addresses:(body.customer.addresses??[]).join("\n")});}else setMessage(body.error??"Account unavailable");},[]);
  useEffect(()=>{void fetch("/api/customer/auth",{cache:"no-store"}).then((r)=>r.json()).then((b:{customer?:Customer|null})=>{if(b.customer){setAuth("signed-in");void load();}else setAuth("signed-out");}).catch(()=>setAuth("signed-out"));},[load]);
  async function authenticate(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage("");const response=await fetch("/api/customer/auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,mode})});const body=await response.json() as {error?:string};if(response.ok){setAuth("signed-in");setForm({name:"",email:"",phone:"",password:""});await load();}else setMessage(body.error??"Account request failed");setBusy(false);}
  async function signOut(){await fetch("/api/customer/auth",{method:"DELETE"});setAuth("signed-out");setPortal(null);setTab("overview");}
  async function saveProfile(event:React.FormEvent){event.preventDefault();setBusy(true);const response=await fetch("/api/customer/auth",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({name:profile.name,phone:profile.phone,addresses:profile.addresses.split("\n")})});const body=await response.json() as {error?:string};setMessage(response.ok?"Profile and delivery addresses updated.":body.error??"Profile update failed");if(response.ok)await load();setBusy(false);}
  async function saveRecord(type:string,title:string,payload:Record<string,unknown>){setBusy(true);const response=await fetch("/api/customer/portal",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type,title,payload})});const body=await response.json() as {error?:string;reference?:string};setMessage(response.ok?`${body.reference} saved to your account.`:body.error??"Could not save record");if(response.ok)await load();setBusy(false);return response.ok;}
  async function requestReturn(event:React.FormEvent){event.preventDefault();const ok=await saveRecord("return",`Return request for ${returnForm.productName||returnForm.orderNumber}`,{...returnForm,requestedAt:new Date().toISOString(),evidence:returnForm.evidence||"No files attached · demo note only"});if(ok)setReturnForm({orderNumber:"",productName:"",reason:"",evidence:""});}
  async function removeRecord(id:string){await fetch("/api/customer/portal",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id})});await load();}
  async function importLocal(type:"saved_build"|"wishlist"){try{if(type==="saved_build"){const selection=JSON.parse(localStorage.getItem("pclogic-builder-selection")??"null") as Record<string,unknown>|null;if(!selection){setMessage("No locally saved build was found on this device.");return;}await saveRecord(type,"My saved PC build",{selection,total:Object.values(selection).reduce((sum,item)=>sum+Number((item as {price?:number})?.price??0),0)});}else{const ids=JSON.parse(localStorage.getItem("pclogic-wishlist")??"[]") as string[];if(!ids.length){setMessage("No locally saved wishlist items were found.");return;}await saveRecord(type,"Imported device wishlist",{productIds:ids});}}catch{setMessage("Local data could not be imported.");}}
  const itemsByOrder=useMemo(()=>portal?.items.reduce<Record<string,Row[]>>((all,item)=>{const key=String(item.order_number);(all[key]??=[]).push(item);return all;}, {})??{},[portal]);const records=(type:string)=>portal?.records.filter((row)=>row.type===type)??[];const spend=portal?.orders.filter((o)=>o.status!=="cancelled").reduce((sum,o)=>sum+Number(o.subtotal)-Number(o.discount??0)+Number(o.shipping_fee??0)+Number(o.service_total??0),0)??0;
  if(auth==="checking")return <main className="commerce-page"><section className="commerce-page-hero"><span>Protected customer space</span><h1>Opening your account…</h1></section></main>;
  if(auth==="signed-out")return <main className="commerce-page"><header className="commerce-page-header"><Link href="/" className="brand"><span>TECH <span>SYSTEMS</span></span></Link><nav><Link href="/shop"><ArrowLeft/>Back to store</Link></nav></header><section className="account-shell"><div className="account-auth"><div className="account-auth-intro"><span className="account-eyebrow">Customer workspace</span><h1>Your builds and orders, remembered.</h1><p>This secure demo account ties together saved builds, wishlist items, quotations, orders, service requests, and warranty records.</p><ul><li><Check/>Thirty-day secure customer session</li><li><Check/>Saved delivery addresses</li><li><Check/>Order and after-sales history</li><li><Check/>No real payment data stored</li></ul></div><div className="account-auth-panel"><div className="account-auth-tabs"><button className={mode==="login"?"active":""} onClick={()=>setMode("login")}>Sign in</button><button className={mode==="register"?"active":""} onClick={()=>setMode("register")}>Create account</button></div><form className="account-form" onSubmit={authenticate}>{mode==="register"&&<><label>Full name<input required value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/></label><label>Mobile number<input required value={form.phone} onChange={(e)=>setForm({...form,phone:e.target.value})}/></label></>}<label className="wide">Email address<input required type="email" autoComplete="email" value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})}/></label><label className="wide">Password<div className="account-password"><input required minLength={mode==="register"?8:1} type={showPassword?"text":"password"} autoComplete={mode==="register"?"new-password":"current-password"} value={form.password} onChange={(e)=>setForm({...form,password:e.target.value})}/><button type="button" onClick={()=>setShowPassword(!showPassword)} aria-label={showPassword?"Hide password":"Show password"}>{showPassword?<EyeOff/>:<Eye/>}</button></div>{mode==="register"&&<small>8+ characters with at least one letter and one number.</small>}</label>{message&&<p className="account-message">{message}</p>}<button disabled={busy}>{busy?"Please wait…":mode==="login"?"Sign in securely":"Create demo account"}</button></form></div></div></section></main>;
  const nav:[Tab,string,typeof Package][]=[["overview","Overview",UserRound],["orders","Orders",ShoppingBag],["builds","Builds & quotes",Boxes],["wishlist","Wishlist",Heart],["returns","Returns & warranty",RotateCcw],["profile","Profile",Settings]];
  return <main className="commerce-page"><header className="commerce-page-header"><Link href="/" className="brand"><span>TECH <span>SYSTEMS</span></span></Link><nav><Link href="/shop"><ArrowLeft/>Store</Link><Link href="/builder">PC Builder</Link></nav></header><section className="commerce-page-hero"><span>Customer command center</span><h1>Welcome back, {portal?.customer.name.split(" ")[0]}.</h1><p>Orders, saved builds, quotations, wishlist items, service bookings, returns, and warranty requests are synchronized here.</p></section><section className="account-shell"><div className="customer-dashboard"><aside className="account-sidebar"><div className="account-profile"><span>{portal?.customer.name.slice(0,1).toUpperCase()}</span><strong>{portal?.customer.name}</strong><small>{portal?.customer.email}</small></div><nav>{nav.map(([key,label,Icon])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}><Icon/>{label}</button>)}</nav><button onClick={signOut}><LogOut/> Sign out</button></aside><section className="account-content">{message&&<p className="account-message">{message}</p>}
    {tab==="overview"&&<><div className="account-content-head"><div><span className="account-eyebrow">Account pulse</span><h1>Everything in one place</h1></div><Link href="/shop"><Plus/>Shop products</Link></div><div className="account-cards"><article className="account-record"><span><strong>{portal?.orders.length??0} website orders</strong><small>Lifetime demo spend {money(spend)}</small></span><aside><b>Orders</b><strong>{portal?.orders.filter((o)=>!["completed","cancelled"].includes(String(o.status))).length} active</strong></aside></article><article className="account-record"><span><strong>{records("saved_build").length} saved builds</strong><small>{records("quote").length} stored quotations</small></span><aside><b>Builder</b><button onClick={()=>setTab("builds")}>Open</button></aside></article><article className="account-record"><span><strong>{records("wishlist").length} wishlist collections</strong><small>Synced from product pages and this device</small></span><aside><b>Saved</b><button onClick={()=>setTab("wishlist")}>View</button></aside></article><article className="account-record"><span><strong>{records("return").length+records("warranty").length} after-sales records</strong><small>Return, warranty, and service status</small></span><aside><b>Support</b><button onClick={()=>setTab("returns")}>Open</button></aside></article></div></>}
    {tab==="orders"&&<><div className="account-content-head"><div><span className="account-eyebrow">Purchase history</span><h1>Your orders</h1></div><Link href="/track"><RefreshCw/>Track order</Link></div><div className="account-cards">{portal?.orders.map((order)=><article className="account-order" key={String(order.order_number)}><span><strong>{String(order.order_number)}</strong><small>{String(order.branch??order.fulfillment)} · {date(order.created_at)}</small></span><aside><b>{String(order.status)}</b><strong>{money(Number(order.subtotal)-Number(order.discount??0)+Number(order.shipping_fee??0)+Number(order.service_total??0))}</strong></aside><div className="account-order-lines">{(itemsByOrder[String(order.order_number)]??[]).map((item)=><div key={`${item.product_id}`}><span>{Number(item.quantity)} × {String(item.product_name)}</span><b>{money(Number(item.quantity)*Number(item.unit_price))}</b></div>)}<Link href={`/track?order=${order.order_number}`}>Open tracking</Link></div></article>)}{!portal?.orders.length&&<Empty icon={ShoppingBag} text="No orders yet" detail="Orders placed using this account email will appear here."/>}</div></>}
    {tab==="builds"&&<><div className="account-content-head"><div><span className="account-eyebrow">Build library</span><h1>Builds & quotations</h1></div><Link href="/builder"><Plus/>New build</Link></div><div className="account-cards"><article className="account-editor"><h2>Import a build from this device</h2><p>Bring the PC Builder selection saved in this browser into your customer account.</p><button onClick={()=>void importLocal("saved_build")}><Boxes/> Import saved build</button></article>{[...records("saved_build"),...records("quote")].map((record)=><RecordCard key={String(record.id)} row={record} onRemove={removeRecord}/>)}{!records("saved_build").length&&!records("quote").length&&<Empty icon={FileText} text="No account builds or quotes yet" detail="Save from the builder or quotation page to keep it here."/>}</div></>}
    {tab==="wishlist"&&<><div className="account-content-head"><div><span className="account-eyebrow">Saved products</span><h1>Your wishlist</h1></div><Link href="/shop"><Plus/>Browse products</Link></div><div className="account-cards"><article className="account-editor"><h2>Sync this device</h2><p>Import wishlist products saved before you signed in.</p><button onClick={()=>void importLocal("wishlist")}><Heart/> Import device wishlist</button></article>{records("wishlist").map((record)=><RecordCard key={String(record.id)} row={record} onRemove={removeRecord}/>)}</div></>}
    {tab==="returns"&&<><div className="account-content-head"><div><span className="account-eyebrow">After-sales support</span><h1>Returns & warranty</h1></div></div><div className="account-cards"><article className="account-editor"><h2>Create a demo return request</h2><form onSubmit={requestReturn}><select required value={returnForm.orderNumber} onChange={(e)=>setReturnForm({...returnForm,orderNumber:e.target.value})}><option value="">Select an order</option>{portal?.orders.map((order)=><option key={String(order.order_number)} value={String(order.order_number)}>{String(order.order_number)}</option>)}</select><input required value={returnForm.productName} onChange={(e)=>setReturnForm({...returnForm,productName:e.target.value})} placeholder="Product name"/><textarea required value={returnForm.reason} onChange={(e)=>setReturnForm({...returnForm,reason:e.target.value})} placeholder="Describe the concern, symptoms, and requested resolution"/><input value={returnForm.evidence} onChange={(e)=>setReturnForm({...returnForm,evidence:e.target.value})} placeholder="Evidence note (demo — no real upload required)"/><button disabled={busy}><ShieldCheck/> Submit return request</button></form></article>{[...records("return"),...records("warranty"),...records("service_booking")].map((record)=><RecordCard key={String(record.id)} row={record} onRemove={removeRecord}/>)}{!records("return").length&&!records("warranty").length&&!records("service_booking").length&&<Empty icon={Wrench} text="No after-sales requests" detail="A new request will appear here and in the admin dashboard."/>}</div></>}
    {tab==="profile"&&<><div className="account-content-head"><div><span className="account-eyebrow">Account settings</span><h1>Profile & addresses</h1></div></div><article className="account-editor"><form onSubmit={saveProfile}><input required value={profile.name} onChange={(e)=>setProfile({...profile,name:e.target.value})} placeholder="Full name"/><input required value={profile.phone} onChange={(e)=>setProfile({...profile,phone:e.target.value})} placeholder="Mobile number"/><textarea value={profile.addresses} onChange={(e)=>setProfile({...profile,addresses:e.target.value})} placeholder="One delivery address per line"/><button disabled={busy}><Settings/> Save account details</button></form></article></>}
    </section></div></section></main>;
}

function Empty({icon:Icon,text,detail}:{icon:typeof Package;text:string;detail:string}){return <div className="account-empty"><Icon/><h2>{text}</h2><p>{detail}</p></div>}
function RecordCard({row,onRemove}:{row:Row;onRemove:(id:string)=>void}){const payload=parse(row.payload);return <article className="account-record" key={String(row.id)}><span><strong>{String(row.title)}</strong><small>{String(row.reference)} · {date(row.updated_at)} · {Object.entries(payload).slice(0,2).map(([k,v])=>`${k}: ${typeof v==="object"?"saved details":String(v)}`).join(" · ")}</small></span><aside><b>{String(row.status)}</b><button onClick={()=>onRemove(String(row.id))}>Remove</button></aside></article>}
