"use client";

import { ArrowLeft, ArrowRight, Check, CreditCard, Filter, Heart, Landmark, Minus, PackageCheck, Plus, Printer, Search, ShieldCheck, ShoppingBag, SlidersHorizontal, Smartphone, Sparkles, Store, Truck, X } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ProductVisual } from "@/components/product-visual";
import { branches, storeProducts, type StoreProduct } from "@/lib/store-data";
import "./shop-commerce.css";
import "./premium-shop.css";

type CatalogProduct=StoreProduct&{quantity:number;reserved:number;specs_json?:string;warranty_months?:number};
type ApiProduct=Record<string,string|number|null>;
type Promotion={id:string;title:string;branch_id?:string;payload:string;reference:string};
type Customer={id:string;email:string;name:string;phone:string;addresses?:string[]};
const includedBuild:Record<string,{id:string;name:string;category:string;price:number}>={integrated:{id:"integrated",name:"Integrated Radeon Graphics",category:"Graphics",price:0},"stock-cooler":{id:"stock-cooler",name:"AMD Stock Air Cooler",category:"Cooling",price:0}};
const services=[{id:"assembly",name:"Professional assembly",detail:"Full installation and cable routing",price:1200},{id:"os",name:"OS & driver installation",detail:"Ready-to-use software setup",price:850},{id:"burnin",name:"24-hour burn-in test",detail:"Thermal and stability validation",price:650},{id:"cable",name:"Premium cable management",detail:"Showcase finish and labeled cables",price:450}];
const deliveryZones=[{id:"nearby",name:"Nearby Pampanga",fee:250},{id:"standard",name:"Standard regional",fee:450},{id:"extended",name:"Extended service area",fee:750}];
const peso=(n:number)=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP",maximumFractionDigits:0}).format(n||0);
const normalize=(p:ApiProduct):CatalogProduct=>({id:String(p.id),sku:String(p.sku),name:String(p.name),brand:String(p.brand),category:String(p.category),description:String(p.description??""),price:Number(p.price??0),powerWatts:Number(p.power_watts??0),socket:p.socket?String(p.socket):undefined,memoryType:p.memory_type?String(p.memory_type):undefined,formFactor:p.form_factor?String(p.form_factor):undefined,imageKey:p.image_key?String(p.image_key):undefined,quantity:Number(p.quantity??0),reserved:Number(p.reserved??0),specs_json:p.specs_json?String(p.specs_json):undefined,warranty_months:Number(p.warranty_months??12)});

export default function ShopPage(){
  const [catalog,setCatalog]=useState<CatalogProduct[]>(storeProducts.map((p)=>({...p,quantity:0,reserved:0})));
  const [branchId,setBranchId]=useState(branches[0].id);const [cart,setCart]=useState<Record<string,number>>({});const [includedIds,setIncludedIds]=useState<string[]>([]);const [hydrated,setHydrated]=useState(false);
  const [query,setQuery]=useState("");const [category,setCategory]=useState("All");const [brand,setBrand]=useState("All");const [socket,setSocket]=useState("All");const [memory,setMemory]=useState("All");const [formFactor,setFormFactor]=useState("All");const [priceBand,setPriceBand]=useState("all");const [inStock,setInStock]=useState(false);const [sort,setSort]=useState("featured");
  const [compare,setCompare]=useState<string[]>([]);const [wishlist,setWishlist]=useState<string[]>([]);const [cartOpen,setCartOpen]=useState(false);
  const [fulfillment,setFulfillment]=useState<"pickup"|"delivery">("pickup");const [payment,setPayment]=useState("pay-on-pickup");const [deliveryZone,setDeliveryZone]=useState("standard");const [selectedServices,setSelectedServices]=useState<string[]>([]);
  const [coupon,setCoupon]=useState("");const [appliedCoupon,setAppliedCoupon]=useState<{code:string;discount:number;message:string}|null>(null);const [promotions,setPromotions]=useState<Promotion[]>([]);
  const [form,setForm]=useState({name:"",email:"",phone:"",address:""});const [status,setStatus]=useState<{kind:"idle"|"loading"|"success"|"error";message:string;order?:string}>({kind:"idle",message:""});const [paymentModal,setPaymentModal]=useState(false);
  const [customer,setCustomer]=useState<Customer|null>(null);

  useEffect(()=>{const timer=window.setTimeout(()=>{
    try{setCart(JSON.parse(localStorage.getItem("pclogic-cart-v2")??"{}") as Record<string,number>);setCompare(JSON.parse(localStorage.getItem("pclogic-compare")??"[]") as string[]);setWishlist(JSON.parse(localStorage.getItem("pclogic-wishlist")??"[]") as string[]);setSelectedServices(JSON.parse(localStorage.getItem("pclogic-cart-services")??"[]") as string[]);setIncludedIds(JSON.parse(localStorage.getItem("pclogic-build-included")??"[]") as string[]);}catch{}
    const params=new URLSearchParams(location.search);setQuery(params.get("q")??"");if(params.get("category"))setCategory(params.get("category")!);if(branches.some((item)=>item.id===params.get("branch")))setBranchId(params.get("branch")!);
    const buildIds=(params.get("build")??"").split(",").filter(Boolean);if(buildIds.length){setCart((current)=>({...current,...Object.fromEntries(buildIds.filter((id)=>!includedBuild[id]).map((id)=>[id,1]))}));setIncludedIds(buildIds.filter((id)=>includedBuild[id]));setCartOpen(true);}
    setHydrated(true);
  },0);return()=>clearTimeout(timer);},[]);
  useEffect(()=>{if(hydrated)localStorage.setItem("pclogic-cart-v2",JSON.stringify(cart));},[cart,hydrated]);
  useEffect(()=>{if(hydrated)localStorage.setItem("pclogic-compare",JSON.stringify(compare));},[compare,hydrated]);
  useEffect(()=>{if(hydrated)localStorage.setItem("pclogic-wishlist",JSON.stringify(wishlist));},[wishlist,hydrated]);
  useEffect(()=>{if(hydrated)localStorage.setItem("pclogic-build-included",JSON.stringify(includedIds));},[includedIds,hydrated]);
  useEffect(()=>{if(hydrated)localStorage.setItem("pclogic-cart-services",JSON.stringify(selectedServices));},[selectedServices,hydrated]);
  useEffect(()=>{let cancelled=false;void fetch("/api/customer/auth",{cache:"no-store"}).then((response)=>response.json()).then((body:{customer?:Customer|null})=>{if(cancelled||!body.customer)return;const current=body.customer;setCustomer(current);setForm((existing)=>({name:existing.name||current.name,email:existing.email||current.email,phone:existing.phone||current.phone,address:existing.address||current.addresses?.[0]||""}));}).catch(()=>{});return()=>{cancelled=true};},[]);
  useEffect(()=>{let cancelled=false;void fetch(`/api/catalog?branch=${encodeURIComponent(branchId)}`,{cache:"no-store"}).then((r)=>r.json()).then((b:{products?:ApiProduct[]})=>{if(!cancelled&&b.products?.length)setCatalog(b.products.map(normalize));}).catch(()=>{});void fetch(`/api/commerce?type=promotion&branch=${encodeURIComponent(branchId)}`,{cache:"no-store"}).then((r)=>r.json()).then((b:{records?:Promotion[]})=>{if(!cancelled)setPromotions(b.records??[]);}).catch(()=>{});return()=>{cancelled=true};},[branchId]);

  const categories=["All",...Array.from(new Set(catalog.map((p)=>p.category)))];const brands=["All",...Array.from(new Set(catalog.map((p)=>p.brand)))];
  const products=useMemo(()=>catalog.filter((p)=>{const available=p.quantity-p.reserved;const searchable=`${p.name} ${p.brand} ${p.sku} ${p.description}`.toLowerCase();return (!query||searchable.includes(query.toLowerCase()))&&(category==="All"||p.category===category)&&(brand==="All"||p.brand===brand)&&(socket==="All"||p.socket===socket)&&(memory==="All"||p.memoryType===memory)&&(formFactor==="All"||p.formFactor===formFactor)&&(!inStock||available>0)&&(priceBand==="all"||priceBand==="under5"&&p.price<5000||priceBand==="5to15"&&p.price>=5000&&p.price<=15000||priceBand==="over15"&&p.price>15000);}).sort((a,b)=>sort==="price-low"?a.price-b.price:sort==="price-high"?b.price-a.price:sort==="name"?a.name.localeCompare(b.name):(b.quantity-b.reserved)-(a.quantity-a.reserved)),[catalog,query,category,brand,socket,memory,formFactor,inStock,priceBand,sort]);
  const cartItems=catalog.filter((p)=>cart[p.id]).map((p)=>({...p,cartQuantity:cart[p.id]}));const includedItems=includedIds.map((id)=>includedBuild[id]).filter(Boolean);const itemSubtotal=cartItems.reduce((sum,item)=>sum+item.price*item.cartQuantity,0);const serviceTotal=services.filter((s)=>selectedServices.includes(s.id)).reduce((sum,s)=>sum+s.price,0);const shippingFee=fulfillment==="delivery"?(deliveryZones.find((z)=>z.id===deliveryZone)?.fee??450):0;const discount=appliedCoupon?.discount??0;const grandTotal=itemSubtotal+serviceTotal+shippingFee-discount;const itemCount=cartItems.reduce((sum,item)=>sum+item.cartQuantity,0)+includedItems.length;
  const updateCart=(id:string,delta:number)=>setCart((current)=>{const next={...current,[id]:Math.max(0,(current[id]??0)+delta)};if(!next[id])delete next[id];return next;});
  const toggleCompare=(id:string)=>setCompare((current)=>current.includes(id)?current.filter((item)=>item!==id):current.length<4?[...current,id]:current);
  const toggleWish=(id:string)=>setWishlist((current)=>current.includes(id)?current.filter((item)=>item!==id):[...current,id]);
  function applyCoupon(){const match=promotions.find((promo)=>{try{return String((JSON.parse(promo.payload) as {code?:string}).code??"").toUpperCase()===coupon.trim().toUpperCase();}catch{return false;}});if(!match){setAppliedCoupon({code:"",discount:0,message:"That code is not active for this branch."});return;}const p=JSON.parse(match.payload) as {code:string;kind:string;value:number;minSpend?:number;maxDiscount?:number};if(itemSubtotal<Number(p.minSpend??0)){setAppliedCoupon({code:"",discount:0,message:`Spend at least ${peso(Number(p.minSpend))} to use this offer.`});return;}const amount=p.kind==="percent"?Math.round(itemSubtotal*p.value/100):p.value;setAppliedCoupon({code:p.code,discount:Math.min(amount,p.maxDiscount??amount,itemSubtotal),message:`${p.code} applied successfully.`});}
  function quote(){localStorage.setItem("pclogic-quote-draft",JSON.stringify({source:"Store cart",branch:branches.find((b)=>b.id===branchId)?.name,items:[...cartItems.map((i)=>({name:i.name,quantity:i.cartQuantity,price:i.price})),...includedItems.map((i)=>({name:i.name,quantity:1,price:0}))],services:services.filter((s)=>selectedServices.includes(s.id)),subtotal:itemSubtotal,discount,shippingFee,total:grandTotal}));location.href="/quote";}
  function beginCheckout(){if(!cartItems.length){setStatus({kind:"error",message:"Add at least one in-stock product before checkout."});return;}if(!form.name||!form.email||!form.phone||fulfillment==="delivery"&&!form.address){setStatus({kind:"error",message:"Complete the customer and fulfillment details first."});return;}if(payment==="pay-on-pickup")void submitOrder();else setPaymentModal(true);}
  async function submitOrder(){setPaymentModal(false);setStatus({kind:"loading",message:"Reserving stock and creating your order…"});try{const response=await fetch("/api/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({customerName:form.name,email:form.email,phone:form.phone,fulfillment,paymentMethod:payment,branchId,deliveryAddress:form.address,deliveryZone,couponCode:appliedCoupon?.code,services:selectedServices,buildMetadata:{included:includedItems.map((item)=>item.name)},items:cartItems.map((item)=>({productId:item.id,quantity:item.cartQuantity}))})});const body=await response.json() as {error?:string;orderNumber?:string;paymentStatus?:string};if(!response.ok)throw new Error(body.error??"Order could not be created");sessionStorage.setItem("pclogic-last-order-email",form.email);setStatus({kind:"success",message:`${body.orderNumber} is confirmed with simulated ${body.paymentStatus} payment.`,order:body.orderNumber});setCart({});setIncludedIds([]);setSelectedServices([]);}catch(error){setStatus({kind:"error",message:error instanceof Error?error.message:"Order could not be created"});}}

  return <main className="commerce-shop"><header className="commerce-shop-header"><Link href="/" className="brand"><span>TECH <span>SYSTEMS</span></span></Link><nav><Link href="/"><ArrowLeft/>Home</Link><Link href="/builder">PC Builder</Link><Link href="/ai"><Sparkles/>AI Advisor</Link><Link href="/account">My account</Link><button onClick={()=>setCartOpen(true)}><ShoppingBag/>{itemCount>0&&<b>{itemCount}</b>} Cart</button></nav></header>
    <section className="commerce-shop-hero"><div><span>Branch-connected catalog</span><h1>Hardware with the details exposed.</h1><p>Compare exact specifications, availability, compatibility and fulfillment before anything reaches checkout.</p></div><label><Store/><span>Active inventory view</span><select value={branchId} onChange={(e)=>setBranchId(e.target.value)}>{branches.map((b)=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label></section>
    {promotions.length>0&&<section className="promotion-strip">{promotions.slice(0,3).map((promo)=><article key={promo.id}><span>Live offer</span><strong>{promo.title}</strong><small>{(()=>{try{return String((JSON.parse(promo.payload) as {code?:string}).code??promo.reference);}catch{return promo.reference;}})()}</small></article>)}</section>}
    <section className="commerce-shop-toolbar"><label className="catalog-search"><Search/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search product, brand, SKU or specification"/><button onClick={()=>setQuery("")} aria-label="Clear search"><X/></button></label><div><Link className="shop-ai-link" href={`/ai?q=${encodeURIComponent(query)}`}><Sparkles/> Ask in plain language</Link><SlidersHorizontal/><span>{products.length} matching products</span><select aria-label="Sort products" value={sort} onChange={(e)=>setSort(e.target.value)}><option value="featured">Featured & available</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option><option value="name">Product name</option></select></div></section>
    <div className="commerce-shop-layout"><aside className="shop-filters"><div><Filter/><strong>Refine catalog</strong><button onClick={()=>{setCategory("All");setBrand("All");setSocket("All");setMemory("All");setFormFactor("All");setPriceBand("all");setInStock(false);}}>Reset</button></div><label>Category<select value={category} onChange={(e)=>setCategory(e.target.value)}>{categories.map((item)=><option key={item}>{item}</option>)}</select></label><label>Brand<select value={brand} onChange={(e)=>setBrand(e.target.value)}>{brands.map((item)=><option key={item}>{item}</option>)}</select></label><label>Price<select value={priceBand} onChange={(e)=>setPriceBand(e.target.value)}><option value="all">Any price</option><option value="under5">Under ₱5,000</option><option value="5to15">₱5,000–₱15,000</option><option value="over15">Over ₱15,000</option></select></label><label>CPU socket<select value={socket} onChange={(e)=>setSocket(e.target.value)}><option>All</option><option>AM4</option><option>AM5</option><option>LGA1700</option></select></label><label>Memory<select value={memory} onChange={(e)=>setMemory(e.target.value)}><option>All</option><option>DDR4</option><option>DDR5</option></select></label><label>Form factor<select value={formFactor} onChange={(e)=>setFormFactor(e.target.value)}><option>All</option><option>ATX</option><option>mATX</option></select></label><label className="stock-toggle"><input type="checkbox" checked={inStock} onChange={(e)=>setInStock(e.target.checked)}/><span>In-stock products only</span></label><Link href={`/compare?ids=${compare.join(",")}`} className={compare.length?"compare-ready":"compare-disabled"}>Compare selected <b>{compare.length}/4</b></Link></aside>
      <section className="commerce-products">{products.map((product)=>{const available=product.quantity-product.reserved;return <article key={product.id} className="commerce-product-card"><div className="commerce-product-media"><ProductVisual id={product.id} name={product.name} imageKey={product.imageKey}/><button className={wishlist.includes(product.id)?"active":""} onClick={()=>toggleWish(product.id)} aria-label="Save to wishlist"><Heart/></button><span className={available>3?"stock-good":available>0?"stock-low":"stock-out"}>{available>0?`${available} available at branch`:"Out of stock"}</span></div><div className="commerce-product-copy"><small>{product.brand} · {product.sku}</small><Link href={`/product/${product.id}`}><h2>{product.name}</h2></Link><p>{product.description}</p><div className="spec-chips">{product.socket&&<span>{product.socket}</span>}{product.memoryType&&<span>{product.memoryType}</span>}{product.formFactor&&<span>{product.formFactor}</span>}{Number(product.powerWatts)>0&&<span>{product.powerWatts}W</span>}</div><strong>{peso(product.price)}</strong><small>{product.warranty_months??12}-month demo warranty</small></div><footer><label><input type="checkbox" checked={compare.includes(product.id)} onChange={()=>toggleCompare(product.id)} disabled={!compare.includes(product.id)&&compare.length>=4}/><span>Compare</span></label><Link href={`/product/${product.id}`}>View details</Link><button onClick={()=>{updateCart(product.id,1);setCartOpen(true);}} disabled={available<=0}><Plus/> Add</button></footer></article>})}{!products.length&&<div className="catalog-empty"><PackageCheck/><h2>No products match those filters.</h2><button onClick={()=>{setQuery("");setCategory("All");setBrand("All");}}>Clear filters</button></div>}</section></div>
    <div className={`cart-drawer-backdrop ${cartOpen?"open":""}`} onClick={()=>setCartOpen(false)}/><aside id="cart" className={`commerce-cart-drawer ${cartOpen?"open":""}`}><header><div><span>Protected demo checkout</span><h2>Your order</h2></div><button onClick={()=>setCartOpen(false)} aria-label="Close cart"><X/></button></header><div className="cart-drawer-scroll"><section className="cart-line-items">{cartItems.map((item)=><article key={item.id}><ProductVisual id={item.id} name={item.name} imageKey={item.imageKey}/><span><strong>{item.name}</strong><small>{peso(item.price)} · {item.quantity-item.reserved} branch stock</small></span><div><button onClick={()=>updateCart(item.id,-1)} aria-label={`Decrease ${item.name} quantity`}><Minus/></button><b>{item.cartQuantity}</b><button onClick={()=>updateCart(item.id,1)} aria-label={`Increase ${item.name} quantity`}><Plus/></button></div></article>)}{includedItems.map((item)=><article key={item.id} className="included-line"><Check/><span><strong>{item.name}</strong><small>Included in selected build</small></span><b>₱0</b></article>)}{!itemCount&&<div className="empty-cart"><ShoppingBag/><strong>Your cart is ready for a build.</strong><p>Add products or continue from the PC Builder.</p></div>}</section>
      {itemCount>0&&<><section className="checkout-section"><h3>Build services</h3>{services.map((service)=><label className="service-option" key={service.id}><input type="checkbox" checked={selectedServices.includes(service.id)} onChange={()=>setSelectedServices((current)=>current.includes(service.id)?current.filter((id)=>id!==service.id):[...current,service.id])}/><span><strong>{service.name}</strong><small>{service.detail}</small></span><b>{peso(service.price)}</b></label>)}</section><section className="checkout-section"><h3>Fulfillment</h3><div className="checkout-choice-grid"><button className={fulfillment==="pickup"?"active":""} onClick={()=>setFulfillment("pickup")}><Store/><span><strong>Branch pickup</strong><small>Free</small></span></button><button className={fulfillment==="delivery"?"active":""} onClick={()=>setFulfillment("delivery")}><Truck/><span><strong>Delivery</strong><small>Demo rate</small></span></button></div>{fulfillment==="delivery"&&<label>Delivery area<select value={deliveryZone} onChange={(e)=>setDeliveryZone(e.target.value)}>{deliveryZones.map((zone)=><option value={zone.id} key={zone.id}>{zone.name} · {peso(zone.fee)}</option>)}</select></label>}</section><section className="checkout-section"><h3>Customer details</h3>{customer&&<p className="checkout-customer-note"><Check/>Signed in as {customer.name}. Your saved details are ready.</p>}<div className="checkout-fields"><input placeholder="Full name" value={form.name} onChange={(e)=>setForm({...form,name:e.target.value})}/><input type="email" placeholder="Email address" value={form.email} readOnly={Boolean(customer)} onChange={(e)=>setForm({...form,email:e.target.value})}/><input placeholder="Mobile number" value={form.phone} onChange={(e)=>setForm({...form,phone:e.target.value})}/>{fulfillment==="delivery"&&<textarea placeholder="Complete delivery address" value={form.address} onChange={(e)=>setForm({...form,address:e.target.value})}/>}</div></section><section className="checkout-section"><h3>Simulated payment</h3><div className="payment-options">{[{id:"pay-on-pickup",name:"Pay on pickup",icon:Store},{id:"gcash",name:"GCash",icon:Smartphone},{id:"card",name:"Credit / debit",icon:CreditCard},{id:"home-credit",name:"Home Credit",icon:Landmark}].map(({id,name,icon:Icon})=><button key={id} className={payment===id?"active":""} onClick={()=>setPayment(id)}><Icon/><span>{name}</span></button>)}</div></section><section className="checkout-section coupon-box"><h3>Promotion code</h3><div><input value={coupon} onChange={(e)=>setCoupon(e.target.value.toUpperCase())} placeholder="Enter code"/><button onClick={applyCoupon}>Apply</button></div>{appliedCoupon&&<p className={appliedCoupon.code?"success":"error"}>{appliedCoupon.message}</p>}</section></>}
    </div><footer className="cart-total"><div><span>Products</span><b>{peso(itemSubtotal)}</b></div>{serviceTotal>0&&<div><span>Build services</span><b>{peso(serviceTotal)}</b></div>}{shippingFee>0&&<div><span>Delivery</span><b>{peso(shippingFee)}</b></div>}{discount>0&&<div className="discount"><span>Promotion</span><b>−{peso(discount)}</b></div>}<div className="grand"><span>Demo total<small>Final stock and price confirmed by branch.</small></span><strong>{peso(grandTotal)}</strong></div>{status.kind!=="idle"&&<p className={status.kind}>{status.message}{status.order&&<> <Link href={`/track?order=${status.order}`}>Track order</Link></>}</p>}<div className="checkout-actions"><button onClick={quote} disabled={!itemCount}><Printer/> Quote</button><button onClick={beginCheckout} disabled={!cartItems.length||status.kind==="loading"}><ShieldCheck/>{status.kind==="loading"?"Processing…":"Place demo order"}</button></div></footer></aside>
    {paymentModal&&<div className="demo-payment-modal"><section><ShieldCheck/><span>Safe payment simulation</span><h2>Approve {payment.replaceAll("-"," ")}?</h2><p>No funds, card data, financing application, email, delivery, or external transaction will be created.</p><div><button onClick={()=>setPaymentModal(false)}>Cancel</button><button onClick={()=>void submitOrder()}>Approve demo payment <ArrowRight/></button></div></section></div>}
  </main>;
}
