"use client";

import { ArrowLeft, GitCompare, Heart, MessageCircleQuestion, PackageCheck, Printer, ShieldCheck, ShoppingBag, Star, Store, Wrench } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { ProductVisual } from "@/components/product-visual";
import type { StoreProduct } from "@/lib/store-data";
import "../../commerce-pages.css";

type Row=Record<string,string|number|null>;type Product=StoreProduct&Row;type Community={id:string;title:string;payload:string;created_at:string};
const peso=(n:number)=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP",maximumFractionDigits:0}).format(n||0);
const parse=(value:unknown)=>{try{return JSON.parse(String(value??"{}")) as Record<string,string|number|boolean>;}catch{return {};}};

export default function ProductPage(){
  const params=useParams<{id:string}>();const id=String(params?.id??"");const [product,setProduct]=useState<Product|null>(null);const [stock,setStock]=useState<Row[]>([]);const [catalog,setCatalog]=useState<Product[]>([]);const [reviews,setReviews]=useState<Community[]>([]);const [questions,setQuestions]=useState<Community[]>([]);const [status,setStatus]=useState("");const [communityForm,setCommunityForm]=useState({type:"review",rating:"5",title:"",body:""});
  useEffect(()=>{if(!id)return;let cancelled=false;void Promise.all([fetch(`/api/catalog?id=${encodeURIComponent(id)}`,{cache:"no-store"}).then((r)=>r.json()),fetch("/api/catalog",{cache:"no-store"}).then((r)=>r.json()),fetch(`/api/commerce?type=review&product=${encodeURIComponent(id)}`,{cache:"no-store"}).then((r)=>r.json()),fetch(`/api/commerce?type=question&product=${encodeURIComponent(id)}`,{cache:"no-store"}).then((r)=>r.json())]).then(([detail,all,reviewData,questionData])=>{if(cancelled)return;setProduct((detail as {product?:Product}).product??null);setStock((detail as {stock?:Row[]}).stock??[]);setCatalog(((all as {products?:Product[]}).products??[]));setReviews((reviewData as {records?:Community[]}).records??[]);setQuestions((questionData as {records?:Community[]}).records??[]);}).catch(()=>setStatus("Product details are temporarily unavailable."));return()=>{cancelled=true};},[id]);
  const specs=useMemo(()=>parse(product?.specs_json),[product]);const related=catalog.filter((item)=>item.category===product?.category&&item.id!==id).slice(0,4);const rating=reviews.length?reviews.reduce((sum,item)=>sum+Number(parse(item.payload).rating??0),0)/reviews.length:0;
  function addToCart(){const cart=JSON.parse(localStorage.getItem("pclogic-cart-v2")??"{}") as Record<string,number>;cart[id]=(cart[id]??0)+1;localStorage.setItem("pclogic-cart-v2",JSON.stringify(cart));location.href="/shop#cart";}
  function compare(){const ids=JSON.parse(localStorage.getItem("pclogic-compare")??"[]") as string[];if(!ids.includes(id)&&ids.length<4)ids.push(id);localStorage.setItem("pclogic-compare",JSON.stringify(ids));location.href=`/compare?ids=${ids.join(",")}`;}
  async function wishlist(){const local=JSON.parse(localStorage.getItem("pclogic-wishlist")??"[]") as string[];if(!local.includes(id))local.push(id);localStorage.setItem("pclogic-wishlist",JSON.stringify(local));const response=await fetch("/api/customer/portal",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"wishlist",title:product?.name,payload:{productId:id,productName:product?.name,price:product?.price}})});setStatus(response.ok?"Saved to your account wishlist.":"Saved on this device. Sign in to sync it to your account.");}
  async function submitCommunity(event:React.FormEvent){event.preventDefault();const response=await fetch("/api/commerce",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...communityForm,productId:id,rating:Number(communityForm.rating)})});const body=await response.json() as {error?:string};if(!response.ok){setStatus(body.error??"Sign in to post.");return;}setStatus(communityForm.type==="review"?"Review published.":"Question published for store follow-up.");setCommunityForm({...communityForm,title:"",body:""});const refresh=await fetch(`/api/commerce?type=${communityForm.type}&product=${encodeURIComponent(id)}`).then((r)=>r.json()) as {records?:Community[]};if(communityForm.type==="review")setReviews(refresh.records??[]);else setQuestions(refresh.records??[]);}
  if(!product)return <main className="commerce-page"><header className="commerce-page-header"><Link href="/" className="brand"><span>TECH <span>SYSTEMS</span></span></Link><Link href="/shop"><ArrowLeft/> Back to catalog</Link></header><section className="commerce-page-hero"><span>Loading catalog</span><h1>{status||"Opening product details…"}</h1></section></main>;
  return <main className="commerce-page"><header className="commerce-page-header"><Link href="/" className="brand"><span>TECH <span>SYSTEMS</span></span></Link><nav><Link href="/shop"><ArrowLeft/>Catalog</Link><Link href="/builder">PC Builder</Link><Link href="/account">My account</Link></nav></header>
    <section className="product-detail-shell"><div className="product-gallery"><ProductVisual id={product.id} name={product.name} imageKey={product.image_key?String(product.image_key):product.imageKey}/></div><div className="product-copy"><span>{product.brand} · {product.category} · {product.sku}</span><h1>{product.name}</h1><p>{product.description}</p>{reviews.length>0&&<div className="spec-chips"><span><Star/> {rating.toFixed(1)} from {reviews.length} verified review{reviews.length===1?"":"s"}</span></div>}<div className="product-price-row"><strong>{peso(Number(product.price))}</strong><span><ShieldCheck/>{Number(product.warranty_months??12)}-month warranty</span></div><h3>Branch availability</h3><div className="product-stock-grid">{stock.map((row)=><article key={String(row.branch_id)}><span>{String(row.branch)}</span><strong>{Number(row.available)>0?"Available now":"Confirm with branch"}</strong><b>{Number(row.available)} ready to reserve</b></article>)}</div><div className="product-actions"><button className="primary" onClick={addToCart}><ShoppingBag/>Add to cart</button><button onClick={wishlist}><Heart/>Save</button><button onClick={compare}><GitCompare/>Compare</button><button onClick={()=>{localStorage.setItem("pclogic-quote-draft",JSON.stringify({source:"Product quotation",items:[{name:product.name,quantity:1,price:Number(product.price)}],subtotal:Number(product.price),discount:0,shippingFee:0,total:Number(product.price)}));location.href="/quote";}}><Printer/>Quote</button></div>{status&&<p className="account-message">{status}</p>}</div></section>
    <section className="product-detail-lower"><div className="product-tabs-grid"><article className="detail-card"><header><h2>Exact specifications</h2><PackageCheck/></header><div className="spec-table">{Object.entries(specs).map(([key,value])=><div key={key}><span>{key}</span><strong>{String(value)}</strong></div>)}{product.socket&&<div><span>Socket</span><strong>{product.socket}</strong></div>}{product.memory_type&&<div><span>Memory type</span><strong>{String(product.memory_type)}</strong></div>}{product.form_factor&&<div><span>Form factor</span><strong>{String(product.form_factor)}</strong></div>}{product.power_watts&&<div><span>Power / capacity</span><strong>{String(product.power_watts)}W</strong></div>}</div></article><article className="detail-card"><header><h2>Purchase confidence</h2><ShieldCheck/></header><div className="warranty-list"><div><ShieldCheck/><span><strong>Branch-backed warranty</strong><small>{Number(product.warranty_months??12)} months in this demonstration record.</small></span></div><div><Store/><span><strong>Three-branch visibility</strong><small>Reserve where the product is available.</small></span></div><div><Wrench/><span><strong>Compatibility support</strong><small>Use the builder or ask a branch expert before ordering.</small></span></div><div><PackageCheck/><span><strong>Exact item verification</strong><small>SKU and contents are double-checked before fulfillment.</small></span></div></div></article></div>
      <div className="community-grid"><article className="detail-card"><header><h2>Reviews & questions</h2><MessageCircleQuestion/></header><div className="community-list">{reviews.map((item)=>{const p=parse(item.payload);return <article key={item.id}><span><b>{"★".repeat(Number(p.rating??5))}</b><b>Verified</b></span><p>{String(p.body??"")}</p><small>{String(p.author??"Customer")} · {item.title}</small></article>})}{questions.map((item)=>{const p=parse(item.payload);return <article key={item.id}><span><b>Question</b><b>Store follow-up</b></span><p>{String(p.body??"")}</p><small>{String(p.author??"Customer")}</small></article>})}{!reviews.length&&!questions.length&&<p>No community posts yet. Be the first after signing in.</p>}</div></article><article className="detail-card"><header><h2>Share your experience</h2><Star/></header><form className="community-form" onSubmit={submitCommunity}><select aria-label="Community post type" value={communityForm.type} onChange={(e)=>setCommunityForm({...communityForm,type:e.target.value})}><option value="review">Write a review</option><option value="question">Ask a product question</option></select>{communityForm.type==="review"&&<select aria-label="Review rating" value={communityForm.rating} onChange={(e)=>setCommunityForm({...communityForm,rating:e.target.value})}><option value="5">5 stars</option><option value="4">4 stars</option><option value="3">3 stars</option><option value="2">2 stars</option><option value="1">1 star</option></select>}<input value={communityForm.title} onChange={(e)=>setCommunityForm({...communityForm,title:e.target.value})} placeholder="Short title"/><textarea required value={communityForm.body} onChange={(e)=>setCommunityForm({...communityForm,body:e.target.value})} placeholder="Your review or question"/><button>Publish to demo store</button></form></article></div>
      {related.length>0&&<><h2>Related products</h2><div className="related-products">{related.map((item)=><Link href={`/product/${item.id}`} key={item.id}><ProductVisual id={item.id} name={item.name} imageKey={item.image_key?String(item.image_key):item.imageKey}/><span><strong>{item.name}</strong><small>{peso(Number(item.price))}</small></span></Link>)}</div></>}
    </section>
  </main>;
}
